# Generated by Django 4.0.10 on 2023-11-05 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=254, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notifications/attachments/')),
                ('push_notification', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('mail_sent_to', models.ManyToManyField(blank=True, related_name='noti_mail_sent_to', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ManyToManyField(blank=True, related_name='noti_receiver', to=settings.AUTH_USER_MODEL)),
                ('receiver_group', models.ManyToManyField(blank=True, help_text='Select the group to send the notification to. If you select a group, the notification will be sent to all the users in that group. If you select a user, the notification will be sent to that user only. If you select both, the notification will be sent to both the user and the group.', related_name='noti_receiver_group', to='auth.group')),
                ('seen_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(auto_now=True)),
                ('is_sent', models.BooleanField(default=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.notification')),
            ],
        ),
    ]
